version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - mongo
    environment:
      - NODE_ENV=development

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
